### ISSUE TITLE
Uncaught TypeError: daumtools.userAgent is not a function

### ISSUE THREAD

**Issue by xx4159** [kakao/web2app#20]
타입스크립트에서 web2app 을 import 해서 쓰는 경우, 다음과 같은 에러가 발생합니다.
```
Uncaught TypeError: daumtools.userAgent is not a function
    at web2app-standalone-1.0.9.js:160
```

daumtools 가 다음 코드에서 빈 객체 `{}` 로 바인딩 되어서 그러는 것 같은데요,

https://github.com/kakao/web2app/blob/cf1dce73e897595559c62a7dc7bd1792e515697d/dist/web2app-standalone-1.0.9.js#L309

이런경우 어떻게 해결하면 되나요?
이건 좀 무식한 방법 같은데, 좋은 방법 있을까요?

```
})(window.daumtools = (typeof window.daumtools === 'undefined') ? exports.daumtools : window.daumtools);
```

고맙습니다 :)

**Comment by dduskim** [comment]
적절한 해결방법을 찾아 업데이트 하도록 하겠습니다. 감사합니다 :)

**Comment by dduskim** [comment]
모듈로더에 대한 처리가 부족했네요.
임시적인 처리를 먼저했구요, 모듈을 사용하는 쪽으로 개선토록 해야겠네요.

21d34822735e4a76e8c453e3e1f0dd22a4792e42
